menu.add_player_feature("still a shit crash lol", "action", 0, function(playerfeat, pid)
    entity.freeze_entity(player.get_player_ped(pid), true)
    local X = object.create_world_object(3613262246, player.get_player_coords(pid), true, false)    
    system.yield(25)
    menu.notify("deleting pizza")
    entity.delete_entity(X)
    system.yield(25)
    menu.notify("done")
end)